[build]
    command = "npm run generate"
    functions = "functions"
    publish = "dist"

[dev]
    command = "npm run dev"
    autoLaunch = true

[[redirects]]
    from = "https://ihealthybox.online/api/*"
    to = "https://ihealthybox.online/.netlify/functions/:splat"
    status = 301
    force = true